<?xml version="1.0" encoding="UTF-8"?>
<!-- ============================================================ -->
<!-- pinEntryScreen.gml                              -->
<!-- ============================================================ -->
<!-- ============================================================ -->
<!-- NOTE: You can optionally associate an "<idname>" element to  -->
<!-- any of the widgets.                                          -->
<!-- The "<idname>" element is required if the application        -->
<!-- business part (written in "C" code) needs to interact with   -->
<!-- the widget.                                                  -->
<!-- The value inside the "<idname>" element must be one of the   -->
<!-- "idname" attributes declared in the "widgetMappings.iml"     -->
<!-- file (located at project root). Please complete this file    -->
<!-- if needed.                                                   -->
<!-- The uniqueness of each <idname> is automatically checked     -->
<!-- (in the editor and at build time).                           -->
<!-- ============================================================ -->
<DAL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ingenico.com/schemas/dal/1_0">
  <version DAL_version="01.00" this_version="01.00"/>
  <goal name="ReviewTx">
    <window>
      <backalign>left</backalign>
      <forealign>left</forealign>
      <textalign>left</textalign>
      <paddings>
        <left>10</left>
        <top>0</top>
        <right>0</right>
        <bottom>0</bottom>
        <unit>perthousand</unit>
      </paddings>
      <children>
        <timer>
          <idname>../widgetMappings.iml#REVIEW_TX_TIMEOUT_TIMER</idname>
        </timer>
        <layout>
          <backalign>center</backalign>
          <forealign>top</forealign>
          <children>
            <label>
              <item>
                <column>1</column>
                <row>0</row>
              </item>
              <grow>width</grow>
              <forealign>left</forealign>
              <textalign>center</textalign>
              <paddings>
                <left>0</left>
                <top>0</top>
                <right>0</right>
                <bottom>0</bottom>
                <unit>%</unit>
              </paddings>
              <position>
                <x>400</x>
                <y>0</y>
                <unit>perthousand</unit>
              </position>
              <minsize>
                <width>243</width>
                <height>120</height>
                <unit>perthousand</unit>
              </minsize>
              <text>REVIEW</text>
            </label>
          </children>
        </layout>
        <label>
          <idname>../widgetMappings.iml#REVIEW_CARD_TYPE</idname>
          <textalign>right</textalign>
          <position>
            <x>500</x>
            <y>150</y>
            <unit>perthousand</unit>
          </position>
          <minsize>
            <width>456</width>
            <height>125</height>
            <unit>perthousand</unit>
          </minsize>
          <text>Card Type</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_MASKED_PAN</idname>
          <textalign>left</textalign>
          <position>
            <x>0</x>
            <y>300</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>712</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>NNNN **** **** NNNN</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_TX_TYPE</idname>
          <textalign>left</textalign>
          <position>
            <x>0</x>
            <y>150</y>
            <unit>perthousand</unit>
          </position>
          <minsize>
            <width>456</width>
            <height>125</height>
            <unit>perthousand</unit>
          </minsize>
          <text>TX TYPE</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_MASKED_EXPIRY_DATE</idname>
          <textalign>right</textalign>
          <position>
            <x>600</x>
            <y>300</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>356</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>**/**</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_TX_AMOUNT</idname>
          <textalign>right</textalign>
          <position>
            <x>500</x>
            <y>450</y>
            <unit>perthousand</unit>
          </position>
          <minsize>
            <width>456</width>
            <height>125</height>
            <unit>perthousand</unit>
          </minsize>
          <text>SGD: 999,999,999.00</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_TX_STAN</idname>
          <textalign>right</textalign>
          <position>
            <x>665</x>
            <y>600</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>293</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>000001</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <textalign>left</textalign>
          <position>
            <x>0</x>
            <y>600</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>259</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>Auth Code:</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <textalign>left</textalign>
          <position>
            <x>0</x>
            <y>450</y>
            <unit>perthousand</unit>
          </position>
          <minsize>
            <width>456</width>
            <height>125</height>
            <unit>perthousand</unit>
          </minsize>
          <text>Amount : </text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <textalign>left</textalign>
          <position>
            <x>500</x>
            <y>600</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>259</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>STAN: </text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
        <label>
          <idname>../widgetMappings.iml#REVIEW_AUTH_CODE</idname>
          <textalign>left</textalign>
          <position>
            <x>250</x>
            <y>600</y>
            <unit>perthousand</unit>
          </position>
          <size>
            <width>218</width>
            <height>133</height>
            <unit>perthousand</unit>
          </size>
          <text>123456</text>
          <font>
            <style>normal</style>
            <size>
              <height>SMALL</height>
            </size>
          </font>
        </label>
      </children>
    </window>
  </goal>
</DAL>